config/routes.rb
Rails.application.routes.draw do
  resources :things

end

app/models/thing.rb
class Thing < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]

  # GET /things
  # GET /things.json
  def index
    @things = Thing.all
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:time, :name, :sex, :age, :location, :category, :job, :money, :search_service, :buy_service_prepare, :buy_service_category, :buy_service_money, :sell_service_purpose, :sell_service_content, :sell_service_type, :sell_service_money, :suggestion, :position)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ttt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/things/_form.html.erb
<%= form_for(@thing) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>调查时间(例如2014/11/11 上午12:00:00)</label>
    <br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <label>姓名</label>
    <br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <label>性别</label>
    <br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <label>年龄</label>
    <br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <label>所在地</label>
    <br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <label>行业</label>
    <br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <label>职业</label>
    <br>
    <%= f.text_field :job %>
  </div>
  <div class="field">
    <label>月可支配收入</label>
    <br>
    <%= f.text_field :money %>
  </div>
  <div class="field">
    <label>寻求服务的渠道(例如朋友圈、微博、百度、知乎)</label>
    <br>
    <%= f.text_area :search_service %>
  </div>
  <div class="field">
    <label>购买服务的前提(例如1、对方的真实性2、服务不满意的时候纠纷处理3、隐私骚扰)</label>
    <br>
    <%= f.text_area :buy_service_prepare %>
  </div>
  <div class="field">
    <label>愿意购买服务的类型(例如心理咨询，旅游，母婴，生活，职业，留学，金融，美容，宠物，法律等)</label>
    <br>
    <%= f.text_area :buy_service_category %>
  </div>
  <div class="field">
    <label>愿意单次支付的金额</label>
    <br>
    <%= f.text_field :buy_service_money %>
  </div>
  <div class="field">
    <label>售卖服务的目的(例如帮助别人，挣钱)</label>
    <br>
    <%= f.text_area :sell_service_purpose %>
  </div>
  <div class="field">
    <label>愿意售卖的服务内容(心理咨询，旅游，母婴，生活，职业，留学，金融，美容，宠物，法律等)</label>
    <br>
    <%= f.text_area :sell_service_content %>
  </div>
  <div class="field">
    <label>愿意售卖服务的形式(例如微信，语音，线下等)</label>
    <br>
    <%= f.text_area :sell_service_type %>
  </div>
  <div class="field">
    <label>服务售卖单价(例如100/时)</label>
    <br>
    <%= f.text_field :sell_service_money %>
  </div>
  <div class="field">
    <label>建议</label>
    <br>
    <%= f.text_area :suggestion %>
  </div>
  <div class="field">
    <label>定位(例如大众服务：医生、律师)</label>
    <br>
    <%= f.text_area :position %>
  </div>
  <div class="actions">
    <%= f.submit "提交问卷" %>
  </div>
<% end %>

app/views/things/edit.html.erb
<h1>Editing thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/index.html.erb
<h1>用户调查结果</h1>

<table>
  <thead>
    <tr>
      <th>访谈时间</th>
      <th>姓名</th>
      <th>性别</th>
      <th>年龄</th>
      <th>所在地</th>
      <th>行业</th>
      <th>职业</th>
      <th>月度可支配收入</th>
      <th>寻求服务的渠道</th>
      <th>购买服务的前提</th>
      <th>愿意购买的服务类型</th>
      <th>愿意单词支付的金额</th>
      <th>售卖服务的目的</th>
      <th>愿意收买的服务内容</th>
      <th>愿意售卖服务的形式</th>
      <th>售卖单价</th>
      <th>建议</th>
      <th>定位</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @things.each do |thing| %>
      <tr>
        <td><%= thing.time %></td>
        <td><%= thing.name %></td>
        <td><%= thing.sex %></td>
        <td><%= thing.age %></td>
        <td><%= thing.location %></td>
        <td><%= thing.category %></td>
        <td><%= thing.job %></td>
        <td><%= thing.money %></td>
        <td><%= thing.search_service %></td>
        <td><%= thing.buy_service_prepare %></td>
        <td><%= thing.buy_service_category %></td>
        <td><%= thing.buy_service_money %></td>
        <td><%= thing.sell_service_purpose %></td>
        <td><%= thing.sell_service_content %></td>
        <td><%= thing.sell_service_type %></td>
        <td><%= thing.sell_service_money %></td>
        <td><%= thing.suggestion %></td>
        <td><%= thing.position %></td>
        <!--<td><%= link_to 'Show', thing %></td>
        <td><%= link_to 'Edit', edit_thing_path(thing) %></td>
        <td><%= link_to 'Destroy', thing, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Thing', new_thing_path %>-->

app/views/things/new.html.erb
<h1>调查问卷</h1>

<%= render 'form' %>

<!--<%= link_to 'Back', things_path %>-->

app/views/things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @thing.time %>
</p>

<p>
  <strong>Name:</strong>
  <%= @thing.name %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @thing.sex %>
</p>

<p>
  <strong>Age:</strong>
  <%= @thing.age %>
</p>

<p>
  <strong>Location:</strong>
  <%= @thing.location %>
</p>

<p>
  <strong>Category:</strong>
  <%= @thing.category %>
</p>

<p>
  <strong>Job:</strong>
  <%= @thing.job %>
</p>

<p>
  <strong>Money:</strong>
  <%= @thing.money %>
</p>

<p>
  <strong>Search service:</strong>
  <%= @thing.search_service %>
</p>

<p>
  <strong>Buy service prepare:</strong>
  <%= @thing.buy_service_prepare %>
</p>

<p>
  <strong>Buy service category:</strong>
  <%= @thing.buy_service_category %>
</p>

<p>
  <strong>Buy service money:</strong>
  <%= @thing.buy_service_money %>
</p>

<p>
  <strong>Sell service purpose:</strong>
  <%= @thing.sell_service_purpose %>
</p>

<p>
  <strong>Sell service content:</strong>
  <%= @thing.sell_service_content %>
</p>

<p>
  <strong>Sell service type:</strong>
  <%= @thing.sell_service_type %>
</p>

<p>
  <strong>Sell service money:</strong>
  <%= @thing.sell_service_money %>
</p>

<p>
  <strong>Suggestion:</strong>
  <%= @thing.suggestion %>
</p>

<p>
  <strong>Position:</strong>
  <%= @thing.position %>
</p>

<!--<%= link_to 'Edit', edit_thing_path(@thing) %> |
<%= link_to 'Back', things_path %>-->